- name: Play1
  hosts: all                                 # mention the name of the inventory group that you want this to be running against
  tasks:
   - name: print hello from play1 of task1
     ansible.builtin.debug:
       msg: hello from task1 of play1

   - name: print hello from play1 of task2
     ansible.builtin.debug:
       msg: hello from task2 of play1



- name: Play1
  hosts: dev                              
  tasks:
   - name: print hello from play2  of task1
     ansible.builtin.debug:
       msg: i am task1 from play2

   