- name : Demo on using variables
  hosts: all
  vars:
    URL: play.google.com                   # Global variable; ALL tasks can inherit this value 
  vars_files: demo-vars.yaml
  vars_prompt:
       -name: url
       prompt: Enter the PURL
  tasks:
       - name: Printing the URL task
         ansible.builtin.debug:
           msg: the value of URL is {{URL}}
       - name: Printing the URL from the task
         ansible.builtin.debug:
           msg: "{{URL}}"
         vars: 
           URL: task.google.com                  # task level variable ;the scope of it is only this task

       - name: Printing the value supplied from command line
         ansible.builtin.debug:
           msg: "{{CMD_URL}}"

       - name: Printing the variables from a file
         ansible.builtin.debug:
           msg: "{{GAME_LIVES}}"

           
       - name: Printing prompt URL
         ansible.builtin.debug:
           msg: "{{PURL}}"



# $URL is bash is eqivalent to {{URL}} in YAML

# command line variables > Local variables > global variable > file variables > prompt variable 

#when to specially use quotes?
# when you are printing only the variable then enclose them in double quotes .