- name : Demo on using variables
  hosts: all
  vars:
    URL: play.google.com                   # Global variable; ALL tasks can inherit this value 
  tasks:
       - name: Printing the URL task
         ansible.builtin.debug:
           msg: the value of URL is {{URL}}
       - name: Printing the URL from the task
         ansible.builtin.debug:
           msg: the value of URL is {{URL}}
         vars: 
           URL: task.google.com                   # task level variable ;the scope of it is only this task


# $URL is bash is eqivalent to {{URL}} in YAML

# Local variables > global variable 

#when to specially use quotes?
# when you are printing only the variable then enclose them in double quotes .