#when to use shell module; whenever you want to excute or do some thing where the appropriate module is not avaliable then only prefer using shell 
- name : Demo on using register
  hosts: all
  tasks:
   - name: Demo on using shell module
     ansible.builtin.shell: uptime
     register: OUT

   - name: printing shell output using OUT variable
     ansible.builtin.debug:
      msg: "{{OUT}}"


#shell module by default dont show you the output ;it just excutes and if you just want to see the output you just need to register the output