- name: Demo on conditions
  hosts: all
  vars:
    action: false
  tasks:
    - name: execute this task when distribution is CentOS
      ansible.builtin.debug:
        msg: welcome to CentOS
      when: ansible_distribution == "CentOS"
        
    - name: execute this task when distribution is ubuntu
      ansible.builtin.debug:
        msg: welcome to ubuntu
      when: ansible_distribution == "ubuntu"
        
    - name: run an action
      ansible.builtin.debug:
        msg: action is true
      when: action
        
      
      
