- name: Demo on conditions
  hosts: all
  tasks:
    - name: excute this task when distribution is Centos
      ansible.builtin.debug:
        msg: welcome to Centos
      when: ansible_distribution == "Centos"
        
    - name: excute this taskwhen distribution is ubuntu
      ansible.builtin.debug:
        msg: welcome to ubuntu
      when: ansible_distribution == "ubuntu"
        
      
