- name: configuring nodejs repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: creating a roboshop user account
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop user account

- name: download and extract the component
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes
  
- name: performing {{COMPONENT}} cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/catalogue/
    state: absent

- name: Copying files to roboshop home directory
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes   

- name: Generating the node modules
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: copying component systemd file
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restarting the service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: yes
    name: "{{COMPONENT}}"