- name: Installing python and dependencies
  ansible.builtin.yum:
    name:
      - botocore
      - boto3
    state: present



- name: copying component systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restarting the service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: yes
    name: "{{COMPONENT}}"