- name: creating a roboshop user account
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop user account
  register: APPUSERINFO

- name: printing
  ansible.builtin.debug:
    msg: "{{APPUSERINFO}}"

