- name: configuring nodejs repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

#calling user task from common role
- name: calling create user role from common
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

- name: calling download and extract role from common
  ansible.builtin.include_role:
    name: common
    tasks_from: download

# call config service role
- name: calling config service role from common
  ansible.builtin.include_role:
    name: common
    tasks_from: config-svc